// frontend/src/app/sample/page.tsx
"use client";

import React, { useCallback, useState } from "react";
import { AuthLogin } from "../api/auth/login";
import { AuthLogout } from "../api/auth/logout";
import { authRegister } from "../api/auth/register";
import { AuthUser } from "../api/auth/user";
import { isErrorResponse } from "../types/api/base";
import { Button } from "./_components/Button/Button";
import { Input } from "./_components/Input/Input";
import styles from "./page.module.css";

const Sample = () => {
  const [auth, setAuth] = useState({
    token: "",
    name: "",
  });

  const [registerInfo, setRegisterInfo] = useState({
    name: "",
    password: "",
  });

  const [loginInfo, setLoginInfo] = useState({
    username: "",
    password: "",
  });

  const handleOnChangeRegister = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setRegisterInfo((prev) => ({ ...prev, [name]: value }));
  }, []);

  const handleOnChangeLogin = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setLoginInfo((prev) => ({ ...prev, [name]: value }));
  }, []);

  const handleRegister = useCallback(async () => {
    try {
      // 登録リクエストの送信
      // 非同期で実行されるため await で待ち受ける
      const response = await authRegister(registerInfo);
      console.log(response);

      // エラー処理
      if (isErrorResponse(response)) {
        return alert(response.errorMessage);
      }

      setAuth((prev) => ({
        ...prev,
        token: response.token,
        name: response.name,
      }));
    } catch (e) {
      // HTTPステータスコードが異常値の場合は例外として検知できる
      console.error(e);
    }
  }, [registerInfo]);

  const handleLogin = useCallback(async () => {
    // ログインリクエストの送信
    // 非同期で実行されるため then で待ち受ける
    try {
      // 登録リクエストの送信
      // 非同期で実行されるため await で待ち受ける
      const loginResponse = await AuthLogin(loginInfo);

      // エラー処理
      if (isErrorResponse(loginResponse)) {
        return alert(loginResponse.errorMessage);
      }

      const userResponse = await AuthUser();

      // エラー処理
      if (isErrorResponse(userResponse)) {
        return alert(userResponse.errorMessage);
      }
    } catch (e) {
      // HTTPステータスコードが異常値の場合は例外として検知できる
      console.error(e);
    }
  }, [loginInfo]);

  const handleLogout = useCallback(async () => {
    // ログインリクエストの送信
    // 非同期で実行されるため then で待ち受ける
    try {
      // 登録リクエストの送信
      // 非同期で実行されるため await で待ち受ける
      const response = await AuthLogout();
      console.log(response);

      setAuth((prev) => ({
        ...prev,
        token: "",
        name: "",
        email: "",
      }));
    } catch (e) {
      // HTTPステータスコードが異常値の場合は例外として検知できる
      console.error(e);
    }
  }, [auth]);

  return (
    <div className={styles.content}>
      <fieldset className={styles.fieldset}>
        <legend>登録するユーザ情報を入力</legend>
        <div className={styles.form}>
          <p>
            <label>
              名前:
              <Input
                name="name"
                value={registerInfo.name}
                onChange={handleOnChangeRegister}
                type="text"
              />
            </label>
          </p>
          <p>
            <label>
              パスワード:
              <Input
                name="password"
                value={registerInfo.password}
                onChange={handleOnChangeRegister}
                type="password"
              />
            </label>
          </p>
        </div>
        <Button type="button" className={styles.button} onClick={handleRegister}>
          登録
        </Button>
      </fieldset>
      <fieldset className={styles.fieldset}>
        <legend>ログインを行うユーザ情報を入力</legend>
        <div className={styles.form}>
          <p>
            <label>
              ユーザID:
              <Input
                name="username"
                value={loginInfo.username}
                onChange={handleOnChangeLogin}
                type="text"
              />
            </label>
          </p>
          <p>
            <label>
              パスワード:
              <Input
                name="password"
                value={loginInfo.password}
                onChange={handleOnChangeLogin}
                type="password"
              />
            </label>
          </p>
        </div>
        <Button type="button" className={styles.button} onClick={handleLogin}>
          ログイン
        </Button>
      </fieldset>
      <fieldset className={styles.fieldset}>
        <legend>最後にログインを行った認証情報</legend>
        <div className={styles.form}>
          <p>
            アクセストークン:
            <span>{auth.token}</span>
          </p>
          <p>
            名前:
            <span>{auth.name}</span>
          </p>
        </div>
        <Button type="button" className={styles.button} onClick={handleLogout}>
          ログアウト
        </Button>
      </fieldset>
    </div>
  );
};

export default Sample;

// frontend/pages/sample.vue
<template>
  <div class="content">
    <fieldset>
      <legend>登録するユーザ情報を入力</legend>
      <div>
        <p>
          <label>
            名前:
            <input v-model="registerInfo.name" type="text" />
          </label>
        </p>
        <p>
          <label>
            メールアドレス:
            <input v-model="registerInfo.email" type="email" />
          </label>
        </p>
        <p>
          <label>
            パスワード:
            <input v-model="registerInfo.password" type="password" />
          </label>
        </p>
      </div>
      <button type="button" @click="register">登録</button>
    </fieldset>
    <fieldset>
      <legend>ログインを行うユーザ情報を入力</legend>
      <div>
        <p>
          <label>
            メールアドレス:
            <input v-model="loginInfo.email" type="email" />
          </label>
        </p>
        <p>
          <label>
            パスワード:
            <input v-model="loginInfo.password" type="password" />
          </label>
        </p>
      </div>
      <button type="button" @click="login">ログイン</button>
    </fieldset>
    <fieldset>
      <legend>最後にログインを行った認証情報</legend>
      <div>
        <p>
          アクセストークン:
          <span>{{ authInfo.token }}</span>
        </p>
        <p>
          名前:
          <span>{{ authInfo.name }}</span>
        </p>
        <p>
          メールアドレス:
          <span>{{ authInfo.email }}</span>
        </p>
      </div>
      <button type="button" @click="logout">ログアウト</button>
    </fieldset>
  </div>
</template>

<script setup lang="ts">
import type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  UserResponse,
} from "~/types/api/auth";

const { $auth } = useNuxtApp();
const registerInfo = ref<RegisterRequest>({
  name: "",
  email: "",
  password: "",
});
const loginInfo = ref<LoginRequest>({
  email: "",
  password: "",
});
const authInfo = ref<LoginResponse & UserResponse>({
  token: "",
  name: "",
  email: "",
});

type PropertyInfo = { name: string; type: string };
const loginResponseProperties: PropertyInfo[] = [
  { name: "token", type: "string" },
];
const userResponseProperties: PropertyInfo[] = [
  { name: "name", type: "string" },
  { name: "email", type: "string" },
];

/**
 * @function ユーザ情報登録
 */
async function register() {
  try {
    // 登録リクエストの送信
    // 非同期で実行されるため await で待ち受ける
    const response = await $auth.register(registerInfo.value);
    console.log(response);

    // レスポンスの型チェック
    // 登録が正常に行われた場合は LoginResponse & UserResponse が、そうでない場合は ErrorResponse が返る
    if (is<(LoginResponse & UserResponse)>(response, loginResponseProperties)) {
      authInfo.value.token = response.token;
      authInfo.value.name = response.name;
      authInfo.value.email = response.email;
      // ユーザ登録と同時にログイン処理が実行される（詳細はバックエンドの実装を参照）
    } else {
      // 登録失敗時の処理を実装する
    }
  } catch (e) {
    // HTTPステータスコードが異常値の場合は例外として検知できる
    console.log(e);
  }
}

/**
 * @function ログイン
 */
async function login() {
  try {
    // メールアドレス/パスワードを用いてログインを試みる
    const response = await $auth.login(loginInfo.value);
    console.log(response);

    // レスポンスの型チェック
    // ログインが正常に行われた場合は LoginResponse が、そうでない場合は ErrorResponse が返る
    if (is<LoginResponse>(response, loginResponseProperties)) {
      authInfo.value.token = response.token;
      // レスポンスのトークンを使用してログイン中のユーザ情報を取得する
      await getUserInfo();
    } else {
      // ログイン失敗時の処理を実装する
    }
  } catch (e) {
    // HTTPステータスコードが異常値の場合は例外として検知できる
    console.log(e);
  }
}

/**
 * @function ログイン情報取得
 */
async function getUserInfo() {
  try {
    // ログインレスポンスのトークンを用いてログイン情報を取得する
    // トークンは諸説あるが画面の変数ではなく state や storage に持った方がよい
    // その際、トークンは引数で受け付けるよりは $auth.user 側で参照するように実装を修正すべき
    // https://qiita.com/NewGyu/items/0b3111b61405366a76c5
    const response = await $auth.user(authInfo.value.token);
    console.log(response);

    // レスポンスの型チェック
    // 登録が正常に行われた場合は UserResponse が、そうでない場合は ErrorResponse が返る
    if (is<UserResponse>(response, userResponseProperties)) {
      authInfo.value.name = response.name;
      authInfo.value.email = response.email;
    } else {
      // ログイン情報取得失敗時の処理を実装する
    }
  } catch (e) {
    // HTTPステータスコードが異常値の場合は例外として検知できる
    console.log(e);
  }
}

/**
 * @function ログイン情報取得
 */
async function logout() {
  try {
    // ログインレスポンスのトークンを用いてログアウトする
    // こちらもトークンは引数で受け付けるよりは $auth.logout 側で参照するように実装を修正すべき
    const response = await $auth.logout(authInfo.value.token);
    console.log(response);
    authInfo.value.token = "";
    authInfo.value.name = "";
    authInfo.value.email = "";
  } catch (e) {
    console.log(e);
  }
}

/**
 * @function 型ガード関数
 * @summary T に指定された型が properties に定義されているプロパティの型と名前が一致しているかを判定する。<br>すべてが一致している場合 response は T 型のオブジェクトとして扱うことができる。
 */
function is<T extends object>(
  response: ErrorResponse | T,
  properties: PropertyInfo[],
): response is T {
  return properties.every(
    (x) =>
      // プロパティ名の判定
      Reflect.has(response, x.name) &&
      // 型の判定
      typeof Reflect.get(response, x.name) === x.type,
  );
}
</script>

<style>
.content {
  display: flex;
  flex-direction: column;
  gap: 32px;
}
</style>
